{{- if .Values.serviceAccount.create -}}
{{- if or .Values.app.enabled .Values.ui.enabled .Values.docs.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bifrost.serviceAccountName" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.sync.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bifrost.sync.serviceAccountName" . }}
  labels:
    {{- include "bifrost.sync.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- end -}}
